apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: vulnado-pipeline
spec:
  description: |
    Pipeline that clones a Git repo, builds it, runs Sonatype IQ evaluation, and performs Fortify SAST scan.
  params:
    - name: repo-url
      type: string
      description: The Git repository URL.
    - name: revision
      type: string
      default: master
    - name: nexus-iq-url
      type: string
      default: "http://34.1.41.80:8070"
    - name: nexus-iq-username
      type: string
      default: "admin"
    - name: app-id
      type: string
      description: Application id reported to IQ
    - name: ssc-url
      type: string
      default: "http://34.1.41.80:8081/ssc"
    - name: ssc-application-id
      type: string
      default: "10002"
    - name: sensor-version
      type: string
      default: "25.2"
    - name: ssc-auth-secret
      type: string
      default: "ssc-credentials"
    - name: client-auth-token-secret
      type: string
      default: "client-auth-token-secret"
  workspaces:
    - name: shared-data
      description: Shared workspace for the repo and build artifacts
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone-restricted
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: shared-data

    - name: build-application
      runAfter: ["fetch-source"]
      taskRef:
        name: vulnado-build
      workspaces:
        - name: source
          workspace: shared-data

    - name: sca-evaluate
      runAfter: ["build-application"]
      taskRef:
        name: sca-sonatype-iq
      params:
        - name: nexus-iq-url
          value: $(params.nexus-iq-url)
        - name: iq-application-id
          value: $(params.app-id)
        - name: sonatype-auth-secret
          value: "sca-credentials"
      workspaces:
        - name: source
          workspace: shared-data
        - name: reports
          workspace: shared-data

    - name: sast
      runAfter: ["sca-evaluate"]
      taskRef:
        name: sast
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: ssc-url
          value: $(params.ssc-url)
        - name: ssc-application-id
          value: $(params.ssc-application-id)
        - name: sensor-version
          value: $(params.sensor-version)
        - name: ssc-auth-secret
          value: $(params.ssc-auth-secret)
        - name: client-auth-token-secret
          value: $(params.client-auth-token-secret)
