apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: vulnado-pipeline
spec:
  description: |
    Pipeline that clones a Git repo, builds it, runs Sonatype IQ evaluation,
    performs Fortify SAST scan, lint Dockerfile with Hadolint,
    builds and pushes a Docker image to Docker Hub,
    and finally scans it with Trivy.

  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: master
    - name: nexus-iq-url
      type: string
      default: "http://34.1.41.80:8070"
    - name: nexus-iq-username
      type: string
      default: "admin"
    - name: app-id
      type: string
    - name: ssc-url
      type: string
      default: "http://34.1.41.80:8080/ssc"
    - name: ssc-application-id
      type: string
    - name: sensor-version
      type: string
      default: "25.2"
    - name: ssc-auth-secret
      type: string
      default: "ssc-credentials"
    - name: client-auth-token-secret
      type: string
      default: "client-auth-token-secret"
    - name: run-build
      type: string
      default: "yes"
    - name: dockerhub-username
      type: string
    - name: image-name
      type: string
      default: "vulnado-app"
    - name: image-tag
      type: string
      default: "latest"

  workspaces:
    - name: shared-data

  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone-restricted
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: shared-data

    - name: build-application
      runAfter: ["fetch-source"]
      taskRef:
        name: vulnado-build
      when:
        - input: "$(params.run-build)"
          operator: in
          values: ["false"]
      workspaces:
        - name: source
          workspace: shared-data

    - name: sca-evaluate
      runAfter: ["build-application"]
      taskRef:
        name: sca-sonatype-iq
      when:
        - input: "$(params.run-build)"
          operator: in
          values: ["true"]
      params:
        - name: nexus-iq-url
          value: $(params.nexus-iq-url)
        - name: iq-application-id
          value: $(params.app-id)
        - name: sonatype-auth-secret
          value: "sca-credentials"
      workspaces:
        - name: source
          workspace: shared-data
        - name: reports
          workspace: shared-data

    - name: sast
      runAfter: ["sca-evaluate"]
      taskRef:
        name: sast
      when:
        - input: "$(params.run-build)"
          operator: in
          values: ["true"]
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: ssc-url
          value: $(params.ssc-url)
        - name: ssc-application-id
          value: $(params.ssc-application-id)
        - name: sensor-version
          value: $(params.sensor-version)
        - name: ssc-auth-secret
          value: $(params.ssc-auth-secret)
        - name: client-auth-token-secret
          value: $(params.client-auth-token-secret)

    - name: hadolint-scan
      runAfter: ["sast"]
      taskRef:
        name: hadolint-scan
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: dockerfile-path
          value: "$(workspaces.source.path)/Dockerfile"

    - name: build-docker-image
      runAfter: ["hadolint-scan"]
      taskRef:
        name: build-docker-image
      when:
        - input: "$(params.run-build)"
          operator: in
          values: ["false"]
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: image-name
          value: $(params.image-name)
        - name: image-tag
          value: $(params.image-tag)
        - name: dockerhub-username
          value: $(params.dockerhub-username)

    - name: trivy-scan
      runAfter: ["build-docker-image"]
      taskRef:
        name: trivy-scan
      when:
        - input: "$(params.run-build)"
          operator: in
          values: ["false"]
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: image-name
          value: $(params.image-name)
        - name: image-tag
          value: $(params.image-tag)
        - name: dockerhub-username
          value: $(params.dockerhub-username)
