apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: vulnado-run-
spec:
  pipelineRef:
    name: vulnado-pipeline
  podTemplate:
    container:
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - "ALL"
        seccompProfile:
          type: RuntimeDefault
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
  params:
    - name: repo-url
      value: https://github.com/ScaleSec/vulnado.git
    - name: revision
      value: master
    - name: nexus-iq-url
      value: "http://34.1.41.80:8070"
    - name: nexus-iq-username
      value: "admin"
    - name: app-id
      value: "vulnado"
    - name: ssc-url
      value: "http://34.1.41.80:8081/ssc"
    - name: ssc-application-id
      value: "10002"
    - name: sensor-version
      value: "25.2"
    - name: ssc-auth-secret
      value: "ssc-credentials"
    - name: client-auth-token-secret
      value: "client-auth-token-secret"
