apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: vulnado-run-
spec:
  serviceAccountName: kube-bench-admin
  pipelineRef:
    name: vulnado-pipeline
  podTemplate:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
  params:
    - name: repo-url
      value: https://github.com/ved-asole/eKart-ecommerce-backend
    - name: revision
      value: master
    - name: nexus-iq-url
      value: "http://34.1.41.80:8070"
    - name: nexus-iq-username
      value: "admin"
    - name: app-id
      value: "ekart"
    - name: ssc-url
      value: "http://34.1.41.80:8080/ssc"
    - name: ssc-application-id
      value: "10000"
    - name: sensor-version
      value: "25.2"
    - name: ssc-auth-secret
      value: "ssc-credentials"
    - name: client-auth-token-secret
      value: "client-auth-token-secret"
    - name: image-tag
      value: "latest"
    - name: image-name
      value: "ekart-backend"
    - name: dockerhub-username
      value: "eladwy"
    - name: dast-target-url
      value: "http://34.1.41.80:30006/"
    - name: dast-scan-settings-id
      value: "591ed9ac-b1fe-4135-b3d0-80e40aa0b617"
    
